package org.example.bus_tracker_backend;

import lombok.Data;

@Data
public class RootEntity {
    // @Id
    // @AutoGenerated
    private int rootId;
    private final int STARTING_X = 4;
    private final int ENDING_X = 100;

    public double getY(double x){
        return 800-300*Math.pow(x/1000-0.4, 6) +
                200*Math.pow(x/1000-0.6, 4) +
                100*Math.pow(x/1000-0.5, 2);
    }
}
